/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  safelist: [
      'bg-red-600',
      'hover:bg-red-700',
      'bg-green-500',
      'hover:bg-green-600',
      'bg-yellow-500',
      'hover:bg-yellow-600',
      'bg-gray-400',
      'hover:bg-gray-500',
      'bg-blue-500',
      'hover:bg-blue-600',
      'bg-pink-500',
      'hover:bg-pink-600',
      'bg-purple-500',
      'hover:bg-purple-600',
      'bg-gray-800',
      'hover:bg-gray-900',
      'bg-yellow-300',
      'hover:bg-yellow-400',
      'bg-orange-500',
      'hover:bg-orange-600',
      'hover:bg-gray-600',
  ],
  plugins: [],
};
